### ISSUE TITLE
Need to enable ADFS Verbose Auditing

### ISSUE THREAD

**Issue by PaulTown** [CSS-Identity/ADFS-Diag#1]
The script needs to enable ADFS Verbose Auditing as well as application generated auditing.  Right now it is collecting Security event logs that in many cases do not have any ADFS Auditing events as they are not already enabled by the customer.  The script needs to enable this or prompt the user to allow it to enable this.  We need the ADFS Auditing events as part of this data collection.  It is hard to go back later and ask for all this data collection again because we missed the ADFS Auditing events.

#ADFS Auditing:
Set-AdfsProperties -AuditLevel Verbose

Import-Module ADFS    
Set-ADFSProperties -LogLevel $((Get-ADFSProperties).LogLevel + "SuccessAudits" + "FailureAudits")
auditpol.exe /set /subcategory:"Application Generated" /failure:enable /success:enable

**Comment by ChristianWeisse** [comment]
Hi Paul,

for the troubleshooting we  dont need the Security Audit Events generated by ADFS

the context that generates these audits in the first place is already in the ADFS Tracing/Debug Eventlogs
so they add little value in this

Security Auditing is primarily collected in the hopes the customer has configured Windows Security Auditing for logon events
which sometimes helps understanding certain auth/logon failures on the Windows side of things

auditpol does not work well with GPO based Audit Policies

**Comment by ChristianWeisse** [comment]
Hi Paul,

for the troubleshooting we dont need the Security Audit Events generated by ADFS

the context that generates these audits in the first place is already in the ADFS Tracing/Debug Eventlogs
so they add little value in this

Security Auditing is primarily collected in the hopes the customer has configured Windows Security Auditing for logon events
which sometimes helps understanding certain auth/logon failures on the Windows side of things

auditpol does not work well with GPO based Audit Policies

**Comment by ChristianWeisse** [comment]
whilst the prototype works ..will not implement this for the following reasons
a) if we just run ADFS posh for making the changes in WId it takes up to 5 min to propagate and the script trace needs to first
be run on the primary 
a1) if we  make a modification directly to the DB on the nodes ithas the potential to break the service settings
not to mention that in an SQL deployment the Account running the script needs DBA rights too

b) with the ADFS Sign In Events now fetched by AAD connect Health and pushed to AAD Sign In logs,  Verbose should be enabled  anyway by customers or should be enabled on demand for troubleshooting ahead 

c)will add  a pre-check for Auditing Settings so admins can turn it on by themself
